# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_legendonly.ui'
#
# Created: Sun Aug 23 16:07:28 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LegendOnly(object):
    def setupUi(self, LegendOnly):
        LegendOnly.setObjectName(_fromUtf8("LegendOnly"))
        LegendOnly.resize(387, 419)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LegendOnly.sizePolicy().hasHeightForWidth())
        LegendOnly.setSizePolicy(sizePolicy)
        LegendOnly.setMinimumSize(QtCore.QSize(300, 300))
        LegendOnly.setMaximumSize(QtCore.QSize(519, 670))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(LegendOnly)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 380, 371, 41))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.buttonBox = QtGui.QDialogButtonBox(self.horizontalLayoutWidget_5)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_5.addWidget(self.buttonBox)
        self.frame = QtGui.QFrame(LegendOnly)
        self.frame.setGeometry(QtCore.QRect(10, 70, 371, 191))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 358, 71))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_11.addWidget(self.label_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.maxCustomValue = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.maxCustomValue.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(180)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxCustomValue.sizePolicy().hasHeightForWidth())
        self.maxCustomValue.setSizePolicy(sizePolicy)
        self.maxCustomValue.setMinimumSize(QtCore.QSize(180, 0))
        self.maxCustomValue.setMaximumSize(QtCore.QSize(180, 16777215))
        self.maxCustomValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxCustomValue.setDecimals(3)
        self.maxCustomValue.setMaximum(999999999.0)
        self.maxCustomValue.setObjectName(_fromUtf8("maxCustomValue"))
        self.horizontalLayout_2.addWidget(self.maxCustomValue)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.maxCustomRadius = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.maxCustomRadius.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(180)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxCustomRadius.sizePolicy().hasHeightForWidth())
        self.maxCustomRadius.setSizePolicy(sizePolicy)
        self.maxCustomRadius.setMinimumSize(QtCore.QSize(180, 0))
        self.maxCustomRadius.setMaximumSize(QtCore.QSize(180, 16777215))
        self.maxCustomRadius.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.maxCustomRadius.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxCustomRadius.setPrefix(_fromUtf8(""))
        self.maxCustomRadius.setDecimals(0)
        self.maxCustomRadius.setMaximum(999999999.0)
        self.maxCustomRadius.setObjectName(_fromUtf8("maxCustomRadius"))
        self.horizontalLayout_6.addWidget(self.maxCustomRadius)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.line_4 = QtGui.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(10, 80, 351, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 100, 356, 81))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.legendCustomValues = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.legendCustomValues.setObjectName(_fromUtf8("legendCustomValues"))
        self.verticalLayout_6.addWidget(self.legendCustomValues)
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_6.addWidget(self.label_9)
        self.frame_2 = QtGui.QFrame(LegendOnly)
        self.frame_2.setGeometry(QtCore.QRect(10, 270, 371, 111))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.frame_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 351, 91))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_4.addWidget(self.label_10)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.memoryOutput = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memoryOutput.sizePolicy().hasHeightForWidth())
        self.memoryOutput.setSizePolicy(sizePolicy)
        self.memoryOutput.setChecked(True)
        self.memoryOutput.setObjectName(_fromUtf8("memoryOutput"))
        self.horizontalLayout_4.addWidget(self.memoryOutput)
        self.shapefileOutput = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shapefileOutput.sizePolicy().hasHeightForWidth())
        self.shapefileOutput.setSizePolicy(sizePolicy)
        self.shapefileOutput.setChecked(False)
        self.shapefileOutput.setObjectName(_fromUtf8("shapefileOutput"))
        self.horizontalLayout_4.addWidget(self.shapefileOutput)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.legendFileName = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.legendFileName.setEnabled(False)
        self.legendFileName.setReadOnly(True)
        self.legendFileName.setObjectName(_fromUtf8("legendFileName"))
        self.horizontalLayout_3.addWidget(self.legendFileName)
        self.selectFileName = QtGui.QToolButton(self.verticalLayoutWidget_3)
        self.selectFileName.setEnabled(False)
        self.selectFileName.setObjectName(_fromUtf8("selectFileName"))
        self.horizontalLayout_3.addWidget(self.selectFileName)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.addCanevas = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.addCanevas.setEnabled(False)
        self.addCanevas.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.addCanevas.setChecked(True)
        self.addCanevas.setObjectName(_fromUtf8("addCanevas"))
        self.verticalLayout_3.addWidget(self.addCanevas)
        self.frame_3 = QtGui.QFrame(LegendOnly)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 371, 51))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setLineWidth(1)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayoutWidget_8 = QtGui.QWidget(self.frame_3)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 10, 351, 31))
        self.verticalLayoutWidget_8.setObjectName(_fromUtf8("verticalLayoutWidget_8"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.nbSector = QtGui.QSpinBox(self.verticalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nbSector.sizePolicy().hasHeightForWidth())
        self.nbSector.setSizePolicy(sizePolicy)
        self.nbSector.setMinimum(1)
        self.nbSector.setObjectName(_fromUtf8("nbSector"))
        self.horizontalLayout.addWidget(self.nbSector)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_10.addLayout(self.horizontalLayout)

        self.retranslateUi(LegendOnly)
        QtCore.QMetaObject.connectSlotsByName(LegendOnly)
        LegendOnly.setTabOrder(self.memoryOutput, self.shapefileOutput)
        LegendOnly.setTabOrder(self.shapefileOutput, self.legendFileName)
        LegendOnly.setTabOrder(self.legendFileName, self.addCanevas)

    def retranslateUi(self, LegendOnly):
        LegendOnly.setWindowTitle(_translate("LegendOnly", "Legend for proportional circles", None))
        self.label_2.setText(_translate("LegendOnly", "Scale", None))
        self.label_5.setText(_translate("LegendOnly", "Value", None))
        self.label_4.setText(_translate("LegendOnly", "Radius (in meters)", None))
        self.label_7.setText(_translate("LegendOnly", "Custom values in legend", None))
        self.legendCustomValues.setToolTip(_translate("LegendOnly", "Automatic values if empty (max;max/3;max/9)", None))
        self.label_9.setText(_translate("LegendOnly", "     (Example : 900;300;100)", None))
        self.label_10.setText(_translate("LegendOnly", "Output :", None))
        self.memoryOutput.setText(_translate("LegendOnly", "Memory", None))
        self.shapefileOutput.setText(_translate("LegendOnly", "Shapefile", None))
        self.selectFileName.setText(_translate("LegendOnly", "...", None))
        self.addCanevas.setText(_translate("LegendOnly", "add the legend to the canvas", None))
        self.label.setText(_translate("LegendOnly", "Number of sectors", None))


