# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_proportionalcircles.ui'
#
# Created: Sat Aug 29 20:49:36 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ProportionalCircles(object):
    def setupUi(self, ProportionalCircles):
        ProportionalCircles.setObjectName(_fromUtf8("ProportionalCircles"))
        ProportionalCircles.resize(538, 718)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ProportionalCircles.sizePolicy().hasHeightForWidth())
        ProportionalCircles.setSizePolicy(sizePolicy)
        ProportionalCircles.setMinimumSize(QtCore.QSize(519, 670))
        ProportionalCircles.setMaximumSize(QtCore.QSize(2000, 2000))
        self.tabWidget = QtGui.QTabWidget(ProportionalCircles)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 521, 701))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.frame_3 = QtGui.QFrame(self.tab)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 501, 251))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setLineWidth(1)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayoutWidget_8 = QtGui.QWidget(self.frame_3)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 10, 481, 231))
        self.verticalLayoutWidget_8.setObjectName(_fromUtf8("verticalLayoutWidget_8"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.inputLayer = QtGui.QComboBox(self.verticalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputLayer.sizePolicy().hasHeightForWidth())
        self.inputLayer.setSizePolicy(sizePolicy)
        self.inputLayer.setToolTip(_fromUtf8(""))
        self.inputLayer.setWhatsThis(_fromUtf8(""))
        self.inputLayer.setObjectName(_fromUtf8("inputLayer"))
        self.horizontalLayout.addWidget(self.inputLayer)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.availAttributesLayout = QtGui.QVBoxLayout()
        self.availAttributesLayout.setObjectName(_fromUtf8("availAttributesLayout"))
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.availAttributesLayout.addWidget(self.label_12)
        self.availableAttributes = QtGui.QListWidget(self.verticalLayoutWidget_8)
        self.availableAttributes.setObjectName(_fromUtf8("availableAttributes"))
        self.availAttributesLayout.addWidget(self.availableAttributes)
        self.horizontalLayout_13.addLayout(self.availAttributesLayout)
        self.attributeButtonLayout = QtGui.QVBoxLayout()
        self.attributeButtonLayout.setObjectName(_fromUtf8("attributeButtonLayout"))
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.attributeButtonLayout.addItem(spacerItem1)
        self.btnAdd = QtGui.QPushButton(self.verticalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAdd.sizePolicy().hasHeightForWidth())
        self.btnAdd.setSizePolicy(sizePolicy)
        self.btnAdd.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/themes/default/symbologyAdd.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdd.setIcon(icon)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.attributeButtonLayout.addWidget(self.btnAdd)
        self.btnRemove = QtGui.QPushButton(self.verticalLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRemove.sizePolicy().hasHeightForWidth())
        self.btnRemove.setSizePolicy(sizePolicy)
        self.btnRemove.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/themes/default/symbologyRemove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRemove.setIcon(icon1)
        self.btnRemove.setObjectName(_fromUtf8("btnRemove"))
        self.attributeButtonLayout.addWidget(self.btnRemove)
        spacerItem2 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.attributeButtonLayout.addItem(spacerItem2)
        self.horizontalLayout_13.addLayout(self.attributeButtonLayout)
        self.assignedAttributesLayout = QtGui.QVBoxLayout()
        self.assignedAttributesLayout.setObjectName(_fromUtf8("assignedAttributesLayout"))
        self.Assigened = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.Assigened.setObjectName(_fromUtf8("Assigened"))
        self.assignedAttributesLayout.addWidget(self.Assigened)
        self.selectedAttributes = QtGui.QListWidget(self.verticalLayoutWidget_8)
        self.selectedAttributes.setObjectName(_fromUtf8("selectedAttributes"))
        self.assignedAttributesLayout.addWidget(self.selectedAttributes)
        self.horizontalLayout_13.addLayout(self.assignedAttributesLayout)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.selectedFeatures = QtGui.QCheckBox(self.verticalLayoutWidget_8)
        self.selectedFeatures.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.selectedFeatures.setObjectName(_fromUtf8("selectedFeatures"))
        self.verticalLayout_10.addWidget(self.selectedFeatures)
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(10, 270, 501, 211))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 481, 124))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.autoScale = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.autoScale.setFont(font)
        self.autoScale.setChecked(True)
        self.autoScale.setObjectName(_fromUtf8("autoScale"))
        self.verticalLayout_2.addWidget(self.autoScale)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_6.addWidget(self.label_11)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.analysisLayer = QtGui.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analysisLayer.sizePolicy().hasHeightForWidth())
        self.analysisLayer.setSizePolicy(sizePolicy)
        self.analysisLayer.setObjectName(_fromUtf8("analysisLayer"))
        self.verticalLayout_8.addWidget(self.analysisLayer)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.customScale = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.customScale.setFont(font)
        self.customScale.setObjectName(_fromUtf8("customScale"))
        self.verticalLayout_2.addWidget(self.customScale)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_11.addWidget(self.label_5)
        self.maxCustomValue = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.maxCustomValue.setEnabled(False)
        self.maxCustomValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxCustomValue.setDecimals(3)
        self.maxCustomValue.setMaximum(999999999.0)
        self.maxCustomValue.setObjectName(_fromUtf8("maxCustomValue"))
        self.horizontalLayout_11.addWidget(self.maxCustomValue)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_11.addWidget(self.label_4)
        self.maxCustomRadius = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.maxCustomRadius.setEnabled(False)
        self.maxCustomRadius.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.maxCustomRadius.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxCustomRadius.setPrefix(_fromUtf8(""))
        self.maxCustomRadius.setDecimals(0)
        self.maxCustomRadius.setMaximum(999999999.0)
        self.maxCustomRadius.setObjectName(_fromUtf8("maxCustomRadius"))
        self.horizontalLayout_11.addWidget(self.maxCustomRadius)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.line_4 = QtGui.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(10, 130, 479, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 150, 481, 54))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.legendCustomValues = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.legendCustomValues.setObjectName(_fromUtf8("legendCustomValues"))
        self.verticalLayout_6.addWidget(self.legendCustomValues)
        self.frame_2 = QtGui.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(10, 490, 501, 141))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.frame_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 481, 128))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_4.addWidget(self.label_10)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.memoryOutput = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memoryOutput.sizePolicy().hasHeightForWidth())
        self.memoryOutput.setSizePolicy(sizePolicy)
        self.memoryOutput.setChecked(True)
        self.memoryOutput.setObjectName(_fromUtf8("memoryOutput"))
        self.horizontalLayout_4.addWidget(self.memoryOutput)
        self.shapefileOutput = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shapefileOutput.sizePolicy().hasHeightForWidth())
        self.shapefileOutput.setSizePolicy(sizePolicy)
        self.shapefileOutput.setChecked(False)
        self.shapefileOutput.setObjectName(_fromUtf8("shapefileOutput"))
        self.horizontalLayout_4.addWidget(self.shapefileOutput)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setEnabled(False)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_5.addWidget(self.label_3)
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_8.setEnabled(False)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_5.addWidget(self.label_8)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.circlesFileName = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.circlesFileName.setEnabled(False)
        self.circlesFileName.setReadOnly(True)
        self.circlesFileName.setObjectName(_fromUtf8("circlesFileName"))
        self.horizontalLayout_3.addWidget(self.circlesFileName)
        self.selectFileName = QtGui.QToolButton(self.verticalLayoutWidget_3)
        self.selectFileName.setEnabled(False)
        self.selectFileName.setObjectName(_fromUtf8("selectFileName"))
        self.horizontalLayout_3.addWidget(self.selectFileName)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.legendFileName = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.legendFileName.setEnabled(False)
        self.legendFileName.setReadOnly(True)
        self.legendFileName.setObjectName(_fromUtf8("legendFileName"))
        self.verticalLayout_4.addWidget(self.legendFileName)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.addCanevas = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.addCanevas.setEnabled(False)
        self.addCanevas.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.addCanevas.setChecked(True)
        self.addCanevas.setObjectName(_fromUtf8("addCanevas"))
        self.verticalLayout_3.addWidget(self.addCanevas)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.tab)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 630, 501, 41))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.buttonBox = QtGui.QDialogButtonBox(self.horizontalLayoutWidget_5)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_5.addWidget(self.buttonBox)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.frame_4 = QtGui.QFrame(self.tab_2)
        self.frame_4.setGeometry(QtCore.QRect(10, 70, 501, 191))
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.frame_4)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 481, 71))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_12.addWidget(self.label_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_6.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.legendOnlyMaxCustomValue = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.legendOnlyMaxCustomValue.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(180)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legendOnlyMaxCustomValue.sizePolicy().hasHeightForWidth())
        self.legendOnlyMaxCustomValue.setSizePolicy(sizePolicy)
        self.legendOnlyMaxCustomValue.setMinimumSize(QtCore.QSize(180, 0))
        self.legendOnlyMaxCustomValue.setMaximumSize(QtCore.QSize(180, 16777215))
        self.legendOnlyMaxCustomValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.legendOnlyMaxCustomValue.setDecimals(3)
        self.legendOnlyMaxCustomValue.setMaximum(999999999.0)
        self.legendOnlyMaxCustomValue.setObjectName(_fromUtf8("legendOnlyMaxCustomValue"))
        self.horizontalLayout_2.addWidget(self.legendOnlyMaxCustomValue)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_13.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_10.addWidget(self.label_13)
        self.legendOnlyMaxCustomRadius = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.legendOnlyMaxCustomRadius.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(180)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legendOnlyMaxCustomRadius.sizePolicy().hasHeightForWidth())
        self.legendOnlyMaxCustomRadius.setSizePolicy(sizePolicy)
        self.legendOnlyMaxCustomRadius.setMinimumSize(QtCore.QSize(180, 0))
        self.legendOnlyMaxCustomRadius.setMaximumSize(QtCore.QSize(180, 16777215))
        self.legendOnlyMaxCustomRadius.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.legendOnlyMaxCustomRadius.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.legendOnlyMaxCustomRadius.setPrefix(_fromUtf8(""))
        self.legendOnlyMaxCustomRadius.setDecimals(0)
        self.legendOnlyMaxCustomRadius.setMaximum(999999999.0)
        self.legendOnlyMaxCustomRadius.setObjectName(_fromUtf8("legendOnlyMaxCustomRadius"))
        self.horizontalLayout_10.addWidget(self.legendOnlyMaxCustomRadius)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12.addLayout(self.verticalLayout)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.line_5 = QtGui.QFrame(self.frame_4)
        self.line_5.setGeometry(QtCore.QRect(10, 80, 481, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.frame_4)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 100, 481, 81))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_14.addWidget(self.label_14)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.legendOnlyCustomValues = QtGui.QLineEdit(self.verticalLayoutWidget_6)
        self.legendOnlyCustomValues.setObjectName(_fromUtf8("legendOnlyCustomValues"))
        self.verticalLayout_9.addWidget(self.legendOnlyCustomValues)
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_9.addWidget(self.label_15)
        self.frame_5 = QtGui.QFrame(self.tab_2)
        self.frame_5.setGeometry(QtCore.QRect(10, 10, 501, 51))
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_5.setLineWidth(1)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayoutWidget_9 = QtGui.QWidget(self.frame_5)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(10, 10, 481, 31))
        self.verticalLayoutWidget_9.setObjectName(_fromUtf8("verticalLayoutWidget_9"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_15.addWidget(self.label_16)
        self.legendOnlyNbSector = QtGui.QSpinBox(self.verticalLayoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legendOnlyNbSector.sizePolicy().hasHeightForWidth())
        self.legendOnlyNbSector.setSizePolicy(sizePolicy)
        self.legendOnlyNbSector.setMinimum(1)
        self.legendOnlyNbSector.setObjectName(_fromUtf8("legendOnlyNbSector"))
        self.horizontalLayout_15.addWidget(self.legendOnlyNbSector)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.verticalLayout_11.addLayout(self.horizontalLayout_15)
        self.frame_6 = QtGui.QFrame(self.tab_2)
        self.frame_6.setGeometry(QtCore.QRect(10, 270, 501, 111))
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.frame_6)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 481, 91))
        self.verticalLayoutWidget_7.setObjectName(_fromUtf8("verticalLayoutWidget_7"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_16.addWidget(self.label_17)
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem7)
        self.legendOnlyMemoryOutput = QtGui.QRadioButton(self.verticalLayoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legendOnlyMemoryOutput.sizePolicy().hasHeightForWidth())
        self.legendOnlyMemoryOutput.setSizePolicy(sizePolicy)
        self.legendOnlyMemoryOutput.setChecked(True)
        self.legendOnlyMemoryOutput.setObjectName(_fromUtf8("legendOnlyMemoryOutput"))
        self.horizontalLayout_16.addWidget(self.legendOnlyMemoryOutput)
        self.legendOnlyShapefileOutput = QtGui.QRadioButton(self.verticalLayoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legendOnlyShapefileOutput.sizePolicy().hasHeightForWidth())
        self.legendOnlyShapefileOutput.setSizePolicy(sizePolicy)
        self.legendOnlyShapefileOutput.setChecked(False)
        self.legendOnlyShapefileOutput.setObjectName(_fromUtf8("legendOnlyShapefileOutput"))
        self.horizontalLayout_16.addWidget(self.legendOnlyShapefileOutput)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.legendOnlyFileName = QtGui.QLineEdit(self.verticalLayoutWidget_7)
        self.legendOnlyFileName.setEnabled(False)
        self.legendOnlyFileName.setReadOnly(True)
        self.legendOnlyFileName.setObjectName(_fromUtf8("legendOnlyFileName"))
        self.horizontalLayout_17.addWidget(self.legendOnlyFileName)
        self.legendOnlySelectFileName = QtGui.QToolButton(self.verticalLayoutWidget_7)
        self.legendOnlySelectFileName.setEnabled(False)
        self.legendOnlySelectFileName.setObjectName(_fromUtf8("legendOnlySelectFileName"))
        self.horizontalLayout_17.addWidget(self.legendOnlySelectFileName)
        self.verticalLayout_12.addLayout(self.horizontalLayout_17)
        self.legendOnlyAddCanevas = QtGui.QCheckBox(self.verticalLayoutWidget_7)
        self.legendOnlyAddCanevas.setEnabled(False)
        self.legendOnlyAddCanevas.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.legendOnlyAddCanevas.setChecked(True)
        self.legendOnlyAddCanevas.setObjectName(_fromUtf8("legendOnlyAddCanevas"))
        self.verticalLayout_12.addWidget(self.legendOnlyAddCanevas)
        self.legendOnlyButtonBox = QtGui.QDialogButtonBox(self.tab_2)
        self.legendOnlyButtonBox.setGeometry(QtCore.QRect(8, 390, 501, 27))
        self.legendOnlyButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.legendOnlyButtonBox.setObjectName(_fromUtf8("legendOnlyButtonBox"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))

        self.retranslateUi(ProportionalCircles)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ProportionalCircles)
        ProportionalCircles.setTabOrder(self.inputLayer, self.availableAttributes)
        ProportionalCircles.setTabOrder(self.availableAttributes, self.btnAdd)
        ProportionalCircles.setTabOrder(self.btnAdd, self.btnRemove)
        ProportionalCircles.setTabOrder(self.btnRemove, self.selectedAttributes)
        ProportionalCircles.setTabOrder(self.selectedAttributes, self.selectedFeatures)
        ProportionalCircles.setTabOrder(self.selectedFeatures, self.autoScale)
        ProportionalCircles.setTabOrder(self.autoScale, self.analysisLayer)
        ProportionalCircles.setTabOrder(self.analysisLayer, self.customScale)
        ProportionalCircles.setTabOrder(self.customScale, self.maxCustomValue)
        ProportionalCircles.setTabOrder(self.maxCustomValue, self.maxCustomRadius)
        ProportionalCircles.setTabOrder(self.maxCustomRadius, self.legendCustomValues)
        ProportionalCircles.setTabOrder(self.legendCustomValues, self.memoryOutput)
        ProportionalCircles.setTabOrder(self.memoryOutput, self.shapefileOutput)
        ProportionalCircles.setTabOrder(self.shapefileOutput, self.circlesFileName)
        ProportionalCircles.setTabOrder(self.circlesFileName, self.selectFileName)
        ProportionalCircles.setTabOrder(self.selectFileName, self.legendFileName)
        ProportionalCircles.setTabOrder(self.legendFileName, self.addCanevas)

    def retranslateUi(self, ProportionalCircles):
        ProportionalCircles.setWindowTitle(_translate("ProportionalCircles", "Proportional circles", None))
        self.label.setText(_translate("ProportionalCircles", "Layer", None))
        self.label_12.setText(_translate("ProportionalCircles", "Available attributes", None))
        self.Assigened.setText(_translate("ProportionalCircles", "Selected attributes", None))
        self.selectedFeatures.setToolTip(_translate("ProportionalCircles", "Extend the analysis to the hole layer if selected features", None))
        self.selectedFeatures.setText(_translate("ProportionalCircles", "Extended analysis", None))
        self.autoScale.setToolTip(_translate("ProportionalCircles", "Proportional to the area of a reference polygon-layer", None))
        self.autoScale.setText(_translate("ProportionalCircles", "Automatic scale", None))
        self.label_11.setText(_translate("ProportionalCircles", "Reference layer", None))
        self.customScale.setText(_translate("ProportionalCircles", "Custom scale", None))
        self.label_5.setText(_translate("ProportionalCircles", "Value", None))
        self.label_4.setText(_translate("ProportionalCircles", "Radius (in meters)", None))
        self.label_7.setText(_translate("ProportionalCircles", "Custom values in legend", None))
        self.label_9.setText(_translate("ProportionalCircles", "     (Example : 900;300;100)", None))
        self.legendCustomValues.setToolTip(_translate("ProportionalCircles", "Automatic values if empty (max;max/3;max/9)", None))
        self.label_10.setText(_translate("ProportionalCircles", "Output :", None))
        self.memoryOutput.setText(_translate("ProportionalCircles", "Memory", None))
        self.shapefileOutput.setText(_translate("ProportionalCircles", "Shapefile", None))
        self.label_3.setText(_translate("ProportionalCircles", "Circles", None))
        self.label_8.setText(_translate("ProportionalCircles", "Legend", None))
        self.selectFileName.setText(_translate("ProportionalCircles", "...", None))
        self.addCanevas.setText(_translate("ProportionalCircles", "add the layers to the canvas", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ProportionalCircles", "Analysis + legend", None))
        self.label_2.setText(_translate("ProportionalCircles", "Scale", None))
        self.label_6.setText(_translate("ProportionalCircles", "Value", None))
        self.label_13.setText(_translate("ProportionalCircles", "Radius (in meters)", None))
        self.label_14.setText(_translate("ProportionalCircles", "Custom values in legend", None))
        self.legendOnlyCustomValues.setToolTip(_translate("ProportionalCircles", "Automatic values if empty (max;max/3;max/9)", None))
        self.label_15.setText(_translate("ProportionalCircles", "     (Example : 900;300;100)", None))
        self.label_16.setText(_translate("ProportionalCircles", "Number of sectors", None))
        self.label_17.setText(_translate("ProportionalCircles", "Output :", None))
        self.legendOnlyMemoryOutput.setText(_translate("ProportionalCircles", "Memory", None))
        self.legendOnlyShapefileOutput.setText(_translate("ProportionalCircles", "Shapefile", None))
        self.legendOnlySelectFileName.setText(_translate("ProportionalCircles", "...", None))
        self.legendOnlyAddCanevas.setText(_translate("ProportionalCircles", "add the legend to the canvas", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ProportionalCircles", "Legend only", None))

